function getSuggestions({ query }) {
  const regex = new RegExp(`^${query}`, 'i');
  const suggestions = suggestionData.filter(({ text }) => regex.test(text));
  return suggestions.slice(0, 5);
}

module.exports = { getSuggestions };

const suggestionData = [
  { text: 'Afghanistan' },
  { text: 'Albania' },
  { text: 'Algeria' },
  { text: 'Andorra' },
  { text: 'Angola' },
  { text: 'Antigua & Deps' },
  { text: 'Argentina' },
  { text: 'Armenia' },
  { text: 'Australia' },
  { text: 'Austria' },
  { text: 'Azerbaijan' },
  { text: 'Bahamas' },
  { text: 'Bahrain' },
  { text: 'Bangladesh' },
  { text: 'Barbados' },
  { text: 'Belarus' },
  { text: 'Belgium' },
  { text: 'Belize' },
  { text: 'Benin' },
  { text: 'Bhutan' },
  { text: 'Bolivia' },
  { text: 'Bosnia Herzegovina' },
  { text: 'Botswana' },
  { text: 'Brazil' },
  { text: 'Brunei' },
  { text: 'Bulgaria' },
  { text: 'Burkina' },
  { text: 'Burundi' },
  { text: 'Cambodia' },
  { text: 'Cameroon' },
  { text: 'Canada' },
  { text: 'Cape Verde' },
  { text: 'Central African Rep' },
  { text: 'Chad' },
  { text: 'Chile' },
  { text: 'China' },
  { text: 'Colombia' },
  { text: 'Comoros' },
  { text: 'Congo' },
  { text: 'Congo {Democratic Rep}' },
  { text: 'Costa Rica' },
  { text: 'Croatia' },
  { text: 'Cuba' },
  { text: 'Cyprus' },
  { text: 'Czech Republic' },
  { text: 'Denmark' },
  { text: 'Djibouti' },
  { text: 'Dominica' },
  { text: 'Dominican Republic' },
  { text: 'East Timor' },
  { text: 'Ecuador' },
  { text: 'Egypt' },
  { text: 'El Salvador' },
  { text: 'Equatorial Guinea' },
  { text: 'Eritrea' },
  { text: 'Estonia' },
  { text: 'Ethiopia' },
  { text: 'Fiji' },
  { text: 'Finland' },
  { text: 'France' },
  { text: 'Gabon' },
  { text: 'Gambia' },
  { text: 'Georgia' },
  { text: 'Germany' },
  { text: 'Ghana' },
  { text: 'Greece' },
  { text: 'Grenada' },
  { text: 'Guatemala' },
  { text: 'Guinea' },
  { text: 'Guinea-Bissau' },
  { text: 'Guyana' },
  { text: 'Haiti' },
  { text: 'Honduras' },
  { text: 'Hungary' },
  { text: 'Iceland' },
  { text: 'India' },
  { text: 'Indonesia' },
  { text: 'Iran' },
  { text: 'Iraq' },
  { text: 'Ireland {Republic}' },
  { text: 'Israel' },
  { text: 'Italy' },
  { text: 'Ivory Coast' },
  { text: 'Jamaica' },
  { text: 'Japan' },
  { text: 'Jordan' },
  { text: 'Kazakhstan' },
  { text: 'Kenya' },
  { text: 'Kiribati' },
  { text: 'Korea North' },
  { text: 'Korea South' },
  { text: 'Kosovo' },
  { text: 'Kuwait' },
  { text: 'Kyrgyzstan' },
  { text: 'Laos' },
  { text: 'Latvia' },
  { text: 'Lebanon' },
  { text: 'Lesotho' },
  { text: 'Liberia' },
  { text: 'Libya' },
  { text: 'Liechtenstein' },
  { text: 'Lithuania' },
  { text: 'Luxembourg' },
  { text: 'Macedonia' },
  { text: 'Madagascar' },
  { text: 'Malawi' },
  { text: 'Malaysia' },
  { text: 'Maldives' },
  { text: 'Mali' },
  { text: 'Malta' },
  { text: 'Marshall Islands' },
  { text: 'Mauritania' },
  { text: 'Mauritius' },
  { text: 'Mexico' },
  { text: 'Micronesia' },
  { text: 'Moldova' },
  { text: 'Monaco' },
  { text: 'Mongolia' },
  { text: 'Montenegro' },
  { text: 'Morocco' },
  { text: 'Mozambique' },
  { text: 'Myanmar, {Burma}' },
  { text: 'Namibia' },
  { text: 'Nauru' },
  { text: 'Nepal' },
  { text: 'Netherlands' },
  { text: 'New Zealand' },
  { text: 'Nicaragua' },
  { text: 'Niger' },
  { text: 'Nigeria' },
  { text: 'Norway' },
  { text: 'Oman' },
  { text: 'Pakistan' },
  { text: 'Palau' },
  { text: 'Panama' },
  { text: 'Papua New Guinea' },
  { text: 'Paraguay' },
  { text: 'Peru' },
  { text: 'Philippines' },
  { text: 'Poland' },
  { text: 'Portugal' },
  { text: 'Qatar' },
  { text: 'Romania' },
  { text: 'Russian Federation' },
  { text: 'Rwanda' },
  { text: 'St Kitts & Nevis' },
  { text: 'St Lucia' },
  { text: 'Saint Vincent & the Grenadines' },
  { text: 'Samoa' },
  { text: 'San Marino' },
  { text: 'Sao Tome & Principe' },
  { text: 'Saudi Arabia' },
  { text: 'Senegal' },
  { text: 'Serbia' },
  { text: 'Seychelles' },
  { text: 'Sierra Leone' },
  { text: 'Singapore' },
  { text: 'Slovakia' },
  { text: 'Slovenia' },
  { text: 'Solomon Islands' },
  { text: 'Somalia' },
  { text: 'South Africa' },
  { text: 'South Sudan' },
  { text: 'Spain' },
  { text: 'Sri Lanka' },
  { text: 'Sudan' },
  { text: 'Suriname' },
  { text: 'Swaziland' },
  { text: 'Sweden' },
  { text: 'Switzerland' },
  { text: 'Syria' },
  { text: 'Taiwan' },
  { text: 'Tajikistan' },
  { text: 'Tanzania' },
  { text: 'Thailand' },
  { text: 'Togo' },
  { text: 'Tonga' },
  { text: 'Trinidad & Tobago' },
  { text: 'Tunisia' },
  { text: 'Turkey' },
  { text: 'Turkmenistan' },
  { text: 'Tuvalu' },
  { text: 'Uganda' },
  { text: 'Ukraine' },
  { text: 'United Arab Emirates' },
  { text: 'United Kingdom' },
  { text: 'United States' },
  { text: 'Uruguay' },
  { text: 'Uzbekistan' },
  { text: 'Vanuatu' },
  { text: 'Vatican City' },
  { text: 'Venezuela' },
  { text: 'Vietnam' },
  { text: 'Yemen' },
  { text: 'Zambia' },
  { text: 'Zimbabwe' },
];
